#Generated by Django 3.0.7 on 2020-07-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radiomics_Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=100)),
                ('study_name', models.CharField(max_length=100)),
                ('study_description', models.CharField(max_length=100)),
                ('imaging_type', models.CharField(max_length=100)),
                ('study_creation_date', models.DateTimeField(blank=True, default='2020-07-04 10:45:17')),
                ('ROI_name', models.CharField(max_length=100)),
                ('num_patients', models.CharField(max_length=100)),
            ],
        ),
    ]
