# Generated by Django 3.0.7 on 2020-07-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('radiomics_images_id', models.AutoField(primary_key=True, serialize=False)),
                ('radiomics_images_path', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='radiomics_study',
            name='id',
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-05 16:07:19'),
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='radiomics_study',
            name='radiomics_images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Images'),
            preserve_default=False,
        ),
    ]
