# Generated by Django 3.0.7 on 2020-07-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200705_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='radiomics_images_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='radiomics_images',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-05 17:10:00'),
        ),
    ]
