# Generated by Django 3.0.7 on 2020-07-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200705_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomics_study',
            name='features',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-06 00:18:01'),
        ),
    ]
