# Generated by Django 3.0.7 on 2020-07-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200706_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomics_study',
            name='file_field',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-06 01:22:32'),
        ),
    ]
