# Generated by Django 3.0.7 on 2020-07-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200709_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='num_patients',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-09 19:30:10'),
        ),
    ]
