# Generated by Django 3.0.7 on 2020-07-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200709_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='imaging_type',
            field=models.CharField(choices=[('mri_t1', 'MRI T1'), ('mri_t2', 'MRI T2'), ('dwi', 'DWI'), ('ct', 'CT')], default='green', max_length=6),
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-09 19:34:54'),
        ),
    ]
