# Generated by Django 3.0.8 on 2020-07-10 01:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200710_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='features_family',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('statistical', 'Statistical'), ('morphological', 'Morphological'), ('texture_GLCM', 'Texture GLCM'), ('texture_RLM', 'Texture RLM'), ('texture_SZM', 'Texture SZM')], default=('statistical', 'morphological', 'texture_GLCM', 'texture_RLM', 'texture_SZM'), max_length=62),
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-10 01:25:38'),
        ),
    ]
