# Generated by Django 3.0.8 on 2020-07-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200711_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='imaging_type',
            field=models.CharField(choices=[('mri t1', 'MRI T1'), ('mri t2', 'MRI T2'), ('dwi', 'DWI'), ('ct', 'CT')], default='mri t1', max_length=6),
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-11 18:21:13'),
        ),
    ]
