# Generated by Django 3.0.8 on 2020-07-11 18:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20200711_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='features_family',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('stat', 'Statistical'), ('morph', 'Morphological'), ('glcm', 'Texture GLCM'), ('rlm', 'Texture RLM'), ('szm', 'Texture SZM')], default=('stat', 'morph', 'glcm', 'rlm', 'szm'), max_length=23),
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-11 18:25:54'),
        ),
    ]
