# Generated by Django 3.0.8 on 2020-07-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20200716_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomics_study',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-17 01:25:21'),
        ),
    ]
