# Generated by Django 3.0.8 on 2020-07-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20200717_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiomics_study',
            old_name='username',
            new_name='study_creator',
        ),
        migrations.AddField(
            model_name='radiomics_study',
            name='delete',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-17 01:36:30'),
        ),
    ]
