# Generated by Django 3.0.8 on 2020-07-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20200717_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-17 02:15:15'),
        ),
    ]
