# Generated by Django 3.0.8 on 2020-07-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20200717_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomics_study',
            name='download_features',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-17 04:32:20'),
        ),
    ]
