# Generated by Django 3.0.8 on 2020-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20200717_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='download_features',
            field=models.CharField(default='download_features', max_length=17),
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-17 16:36:50'),
        ),
    ]
