# Generated by Django 3.0.8 on 2020-07-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20200717_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiomics_study',
            old_name='delete',
            new_name='delete_study',
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-17 16:40:19'),
        ),
    ]
