# Generated by Django 3.0.8 on 2020-07-17 18:15

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20200717_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomics_study',
            name='data',
            field=picklefield.fields.PickledObjectField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-17 18:15:25'),
        ),
    ]
