# Generated by Django 3.0.8 on 2020-07-17 18:30

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20200717_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features_Model',
            fields=[
                ('features_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_id', models.CharField(max_length=100)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='radiomics_study',
            name='data',
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-17 18:30:41'),
        ),
    ]
