# Generated by Django 3.0.7 on 2020-07-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_auto_20200718_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_creation_date',
            field=models.DateTimeField(default='2020-07-18 15:22:35'),
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='study_description',
            field=models.CharField(max_length=1000),
        ),
    ]
