# Generated by Django 3.0.7 on 2020-07-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_auto_20200718_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiomics_study',
            old_name='study_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='radiomics_study',
            name='study_creation_date',
        ),
        migrations.AddField(
            model_name='radiomics_study',
            name='creation_date',
            field=models.DateTimeField(default='2020-07-18 17:51:10'),
        ),
    ]
