# Generated by Django 3.0.7 on 2020-07-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_auto_20200718_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiomics_study',
            old_name='description',
            new_name='study_description',
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='creation_date',
            field=models.DateTimeField(default='2020-07-18 17:53:15'),
        ),
    ]
