# Generated by Django 3.0.7 on 2020-07-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_auto_20200718_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiomics_study',
            old_name='features',
            new_name='eval_features',
        ),
        migrations.AlterField(
            model_name='radiomics_study',
            name='creation_date',
            field=models.DateTimeField(default='2020-07-18 17:56:24'),
        ),
    ]
