# Generated by Django 3.0.7 on 2020-07-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_auto_20200718_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='creation_date',
            field=models.DateTimeField(default='2020-07-18 20:08:39'),
        ),
    ]
