# Generated by Django 3.0.7 on 2020-07-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0215_auto_20200718_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='creation_date',
            field=models.DateTimeField(default='2020-07-18 22:32:39'),
        ),
    ]
