# Generated by Django 3.0.7 on 2020-07-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_auto_20200719_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='creation_date',
            field=models.DateTimeField(default='2020-07-19 05:30:40'),
        ),
    ]
