# Generated by Django 3.0.7 on 2020-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0292_auto_20200719_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiomics_study',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
